version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:php7.4-fpm
    volumes:
      - ./www:/var/www/html
      - ./php/config.ini:/usr/local/etc/php/conf.d/config.ini:ro
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_DATABASE:-wordpress}
      WORDPRESS_DB_USER: ${DB_USERNAME:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-secret}

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USERNAME:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-supersecret}

volumes:
  mysql_data:
